import React from 'react'
import RectDOM from 'react-dom'
// import App from './01_base/01_class_component.js'
// import App from './01_base/02_func_component.js'
// import App from './01_base/03_wapper_component.js'
// import App from './01_base/04_style_component.js'
// import App from './01_base/05_event_bind.js'
// import App from './01_base/07_ref.js'
// import App from './01_base/08_status.js'
// import App from './01_base/09_forloop.js'
// import App from './01_base/10_todoList.js'
// import App from './01_base/12_tab.js'
// import App from './01_base/13_state_sync.js'
// import App from './01_base/14_betterScroll.js'
// import App from './01_base/16_props.js'
// import App from './01_base/17_propsFunction.js'
// import App from './01_base/18_form.js'
// import App from './02_advance/01_child2Parent.js'
// import App from './02_advance/02_childParent_form.js'
// import App from './02_advance/03_childParent_form_ref.js'
// import App from './02_advance/04_middlePerson.js'
// import App from './02_advance/05_publishSubscription.js'
import App from './02_advance/06_prov.js'

RectDOM.render(<App/>, document.getElementById("root"))
