import React from 'react'
import RectDOM from 'react-dom'
// import App from './01_base/01_class_component.js'
// import App from './01_base/02_func_component.js'
// import App from './01_base/03_wapper_component.js'
// import App from './01_base/04_style_component.js'
// import App from './01_base/05_event_bind.js'
// import App from './01_base/07_ref.js'
// import App from './01_base/08_status.js'
// import App from './01_base/09_forloop.js'
// import App from './01_base/10_todoList.js'
// import App from './01_base/12_tab.js'
// import App from './01_base/13_state_sync.js'
// import App from './01_base/14_betterScroll.js'
// import App from './01_base/16_props.js'
// import App from './01_base/17_propsFunction.js'
// import App from './01_base/18_form.js'
// import App from './02_advance/01_child2Parent.js'
// import App from './02_advance/02_childParent_form.js'
// import App from './02_advance/03_childParent_form_ref.js'
// import App from './02_advance/04_middlePerson.js'
// import App from './02_advance/05_publishSubscription.js'
// import App from './02_advance/06_prov.js'
// import App from './02_advance/10_slot.js'
//import App from './02_advance/11_NewlifeCycle.js'
//import App from './02_advance/23_newCycleSample'
// import App from './02_advance/25_swiper_sync.js'
// import App from './02_advance/26_swiper_async.js'
// import App from './02_advance/27_swiper_component.js'
// import App from './03_hook/01_useState'
// import App from './03_hook/02_todoList'
// import App from './03_hook/03_useEffect.js'
// import App from './03_hook/04_useEffect_2.js'
// import App from './03_hook/05_useEffect_3.js'
import App from './03_hook/07_useCallback'

RectDOM.render(<App/>, document.getElementById("root"))
